In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 29 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.21 s


In [4]:
import numpy as np
# Генерация случайных данных
data = np.random.rand(2,3)
data

array([[0.97936869, 0.92333189, 0.61407142],
       [0.87304252, 0.78483952, 0.28623588]])

In [5]:
data * 10

array([[9.79368691, 9.23331889, 6.14071418],
       [8.73042521, 7.8483952 , 2.86235878]])

In [6]:
data + data

array([[1.95873738, 1.84666378, 1.22814284],
       [1.74608504, 1.56967904, 0.57247176]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [11]:
import numpy as np
data1 = [1, 5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([1, 5, 8, 0, 1])

In [12]:
data2 = [[5, 2, 3, 4], [1, 6, 7, 8]]
arr2 = np.array(data2)
arr2


array([[5, 2, 3, 4],
       [1, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
arr = np.array([6, 2, 8, 4, 5])
arr.dtype

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -2, -2.6, 0.8, 12.9, 10.1])
arr


array([ 3.7, -2. , -2.6,  0.8, 12.9, 10.1])

In [27]:
arr.astype(np.int32)

array([ 3, -2, -2,  0, 12, 10])

In [29]:
numeric_strings = np.array(['3', '-8.6', '-2'], dtype=np.string_)
numeric_strings.astype(float)

array([ 3. , -8.6, -2. ])

In [30]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
arr = np.array([[3., 2., 6.], [9., 2., 6.]])
arr

array([[3., 2., 6.],
       [9., 2., 6.]])

In [33]:
arr * arr

array([[ 9.,  4., 36.],
       [81.,  4., 36.]])

In [34]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
1 / arr

array([[0.33333333, 0.5       , 0.16666667],
       [0.11111111, 0.5       , 0.16666667]])

In [36]:
arr ** 0.5

array([[1.73205081, 1.41421356, 2.44948974],
       [3.        , 1.41421356, 2.44948974]])

In [37]:
arr2 = np.array([[6., 2., 1.],[7., 15., 12.]])
arr2

array([[ 6.,  2.,  1.],
       [ 7., 15., 12.]])

In [38]:
arr2 > arr

array([[ True, False, False],
       [False,  True,  True]])

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5]

5

In [41]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[5:8] = 15
arr

array([ 0,  1,  2,  3,  4, 15, 15, 15,  8,  9])

In [45]:
arr_slice = arr[5:8]
arr_slice

array([15, 15, 15])

In [47]:
arr_slice[1] = 15345
arr

array([    0,     1,     2,     3,     4,    15, 15345,    15,     8,
           9])

In [48]:
arr_slice[:] = 80
arr

array([ 0,  1,  2,  3,  4, 80, 80, 80,  8,  9])

In [49]:
arr2d = np.array([[6, 2, 4], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [50]:
arr2d[0][2]

4

In [51]:
arr2d[0, 2]

4

In [52]:
arr3d = np.array([[[5, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 5,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0]

array([[5, 2, 3],
       [4, 5, 6]])

In [54]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d[0] = old_values
arr3d

array([[[ 5,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[1, 0]

array([7, 8, 9])

In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

In [59]:
arr

array([ 0,  1,  2,  3,  4, 80, 80, 80,  8,  9])

In [60]:
arr[1:6]

array([ 1,  2,  3,  4, 80])

In [61]:
arr2d

array([[6, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2d[:2]

array([[6, 2, 4],
       [4, 5, 6]])

In [64]:
arr2d[:2,1:]

array([[2, 4],
       [5, 6]])

In [65]:
arr2d[1, :2]

array([4, 5])

In [66]:
arr2d[:2,2]

array([4, 6])

In [67]:
arr2d[:, :1]

array([[6],
       [4],
       [7]])

In [69]:
arr2d[:2, 1:] = 0
arr2d

array([[6, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [73]:
data[names == 'Bob']

array([[ 0.25700362, -0.37325604,  0.53252638,  1.89120056],
       [-0.75373081,  1.49293003,  0.27438728,  0.91792964]])

In [74]:
data[names == 'Bob', 2:]

array([[0.53252638, 1.89120056],
       [0.27438728, 0.91792964]])

In [75]:
data[names == 'Bob', 2]

array([0.53252638, 0.27438728])

In [76]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [77]:
data[~(names == 'Bob')]

array([[ 0.77965322,  1.67934233,  0.13348928, -0.85610556],
       [-1.10915935, -0.26124172, -0.10417218,  1.91390607],
       [ 0.12809454, -0.98123862,  1.44513026, -0.84119841],
       [ 0.16695775,  0.20945671, -1.62247185,  1.44508636],
       [ 2.4477434 ,  0.18663833, -0.49359526, -1.44855174]])

In [78]:
cond = names == 'Bob'
data[~cond]

array([[ 0.77965322,  1.67934233,  0.13348928, -0.85610556],
       [-1.10915935, -0.26124172, -0.10417218,  1.91390607],
       [ 0.12809454, -0.98123862,  1.44513026, -0.84119841],
       [ 0.16695775,  0.20945671, -1.62247185,  1.44508636],
       [ 2.4477434 ,  0.18663833, -0.49359526, -1.44855174]])

In [79]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [80]:
data[mask]

array([[ 0.25700362, -0.37325604,  0.53252638,  1.89120056],
       [-1.10915935, -0.26124172, -0.10417218,  1.91390607],
       [-0.75373081,  1.49293003,  0.27438728,  0.91792964],
       [ 0.12809454, -0.98123862,  1.44513026, -0.84119841]])

In [81]:
data[data < 0] = 0
data

array([[0.25700362, 0.        , 0.53252638, 1.89120056],
       [0.77965322, 1.67934233, 0.13348928, 0.        ],
       [0.        , 0.        , 0.        , 1.91390607],
       [0.        , 1.49293003, 0.27438728, 0.91792964],
       [0.12809454, 0.        , 1.44513026, 0.        ],
       [0.16695775, 0.20945671, 0.        , 1.44508636],
       [2.4477434 , 0.18663833, 0.        , 0.        ]])

In [82]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.77965322, 1.67934233, 0.13348928, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.16695775, 0.20945671, 0.        , 1.44508636],
       [2.4477434 , 0.18663833, 0.        , 0.        ]])

In [83]:
arr = np.empty((8, 4))
for i in range(8):
 arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [86]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [87]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [88]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [89]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [93]:
arr = np.arange(20).reshape((4, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [95]:
arr = np.random.rand(6, 3)
arr

array([[0.69475329, 0.40879723, 0.92748816],
       [0.86374018, 0.69635428, 0.65141589],
       [0.5139226 , 0.33619554, 0.25230812],
       [0.95997152, 0.67392834, 0.37030411],
       [0.55443369, 0.69296234, 0.2954962 ],
       [0.87790657, 0.79703297, 0.98523249]])

In [96]:
np.dot(arr.T, arr)

array([[3.49250766, 2.78913504, 2.7209529 ],
       [2.78913504, 2.33468966, 2.15718465],
       [2.7209529 , 2.15718465, 2.54336254]])

In [97]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [98]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [99]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])