In [3]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [5]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([-2.15333244, -0.37342709, -0.87800867,  1.92977897,  0.12221058,
        0.06450293,  1.70849629, -1.13486626])

In [8]:
y

array([ 0.19281105, -2.92352065,  1.46131324, -0.58018793, -0.21838544,
        0.89909426,  0.29558205, -0.13880351])

In [9]:
np.maximum(x,y)

array([ 0.19281105, -0.37342709,  1.46131324,  1.92977897,  0.12221058,
        0.89909426,  1.70849629, -0.13880351])

In [10]:
arr = np.random.randn(10) * 4
arr

array([ 2.94473213,  1.88817314,  6.95088256,  2.28504378, -5.81019006,
        2.875026  , -4.78580176, -6.87826548,  0.23289611, -0.30981662])

In [11]:
remaider, whole_part = np.modf(arr)
remaider

array([ 0.94473213,  0.88817314,  0.95088256,  0.28504378, -0.81019006,
        0.875026  , -0.78580176, -0.87826548,  0.23289611, -0.30981662])

In [12]:
whole_part

array([ 2.,  1.,  6.,  2., -5.,  2., -4., -6.,  0., -0.])

In [13]:
arr

array([ 2.94473213,  1.88817314,  6.95088256,  2.28504378, -5.81019006,
        2.875026  , -4.78580176, -6.87826548,  0.23289611, -0.30981662])

In [14]:
np.sqrt(arr)

C:\Users\rafil\AppData\Local\Temp/ipykernel_3636/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.71602218, 1.37410812, 2.63645265, 1.51163613,        nan,
       1.69559016,        nan,        nan, 0.48259311,        nan])

In [15]:
np.sqrt(arr, arr)

C:\Users\rafil\AppData\Local\Temp/ipykernel_3636/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.71602218, 1.37410812, 2.63645265, 1.51163613,        nan,
       1.69559016,        nan,        nan, 0.48259311,        nan])

In [16]:
arr

array([1.71602218, 1.37410812, 2.63645265, 1.51163613,        nan,
       1.69559016,        nan,        nan, 0.48259311,        nan])

In [17]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [18]:
result = [(x if c else y)
for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [19]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [20]:
arr = np.random.randn(4, 4)
arr

array([[ 0.69855566, -0.80116536,  1.17337027,  0.99556303],
       [-0.39761829, -2.63389895,  0.49662866, -0.51668439],
       [-0.1248952 ,  0.16704135, -2.67894196, -0.04499365],
       [ 0.81087619, -0.2957336 ,  0.19526304, -1.2157795 ]])

In [21]:
arr > 0

array([[ True, False,  True,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False,  True, False]])

In [22]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2,  2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2],
       [ 2, -2,  2, -2]])

In [23]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.80116536,  2.        ,  2.        ],
       [-0.39761829, -2.63389895,  2.        , -0.51668439],
       [-0.1248952 ,  2.        , -2.67894196, -0.04499365],
       [ 2.        , -0.2957336 ,  2.        , -1.2157795 ]])

In [24]:
arr = np.random.randn(5, 4)
arr

array([[-0.2521769 , -0.67412984, -1.19654179,  0.05962957],
       [-0.01824714,  0.11217641,  2.82022837,  0.11787294],
       [ 1.66855809,  1.11180999, -0.62428495, -1.28700235],
       [-0.63442496, -0.74027808, -1.02678429,  0.45543123],
       [-1.52983981,  1.64228806, -0.73235288,  2.38121507]])

In [25]:
arr.mean()

0.0826573368888901

In [27]:
np.mean(arr)

0.0826573368888901

In [28]:
arr.sum()

1.653146737777802

In [29]:
arr.mean(axis=1)

array([-0.51580474,  0.75800765,  0.2172702 , -0.48651403,  0.44032761])

In [30]:
arr.sum(axis=0)

array([-0.76613071,  1.45186654, -0.75973555,  1.72714646])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [34]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [35]:
arr = np.random.randn(100)
(arr > 0).sum() # количество положительных значений

54

In [36]:
bools = np.array([False, False, True, False])
bools.any()

True

In [37]:
bools.all()

False

In [38]:
arr = np.random.randn(6)
arr

array([-1.96779553,  0.54437844,  1.53744187,  1.2355482 ,  1.68267512,
        1.02987769])

In [39]:
arr.sort()
arr

array([-1.96779553,  0.54437844,  1.02987769,  1.2355482 ,  1.53744187,
        1.68267512])

In [40]:
arr = np.random.randn(5, 3)
arr

array([[-0.62740407, -0.40326629,  0.34954431],
       [-0.43370855, -1.52361868, -0.95722556],
       [-1.43208634,  0.60646916, -0.42708307],
       [ 0.40031177, -1.35640889, -0.13857235],
       [ 0.69175234,  1.45866668, -0.2782212 ]])

In [41]:
arr.sort(1)
arr

array([[-0.62740407, -0.40326629,  0.34954431],
       [-1.52361868, -0.95722556, -0.43370855],
       [-1.43208634, -0.42708307,  0.60646916],
       [-1.35640889, -0.13857235,  0.40031177],
       [-0.2782212 ,  0.69175234,  1.45866668]])

In [42]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5%ый квантиль

-1.5853608611341505

In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob',
 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [44]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4 ,4])
np.unique(ints)

array([1, 2, 3, 4])

In [45]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [46]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [47]:
arr = np.arange(10)
np.save('some_array', arr)

In [48]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.savez('array_archive.npz', a=arr, b=arr)

In [50]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [52]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [53]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [54]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [55]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [56]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [57]:
x @ np.ones(3)

array([ 6., 15.])

In [58]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 1.2376173 , -1.4883879 ,  0.00964788, -2.39625689,  0.3924207 ],
       [-1.4883879 ,  3.27895328, -0.25910508,  3.02209175,  0.26535814],
       [ 0.00964788, -0.25910508,  0.6460487 ,  0.1924287 ,  0.25670307],
       [-2.39625689,  3.02209175,  0.1924287 ,  5.71513385, -0.23795295],
       [ 0.3924207 ,  0.26535814,  0.25670307, -0.23795295,  1.40376951]])

In [59]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.06754080e-16, -4.91243370e-17,
        -2.66443815e-15,  8.61700090e-17],
       [-6.42030250e-17,  1.00000000e+00,  8.67663183e-18,
        -1.37338069e-15,  2.29417720e-17],
       [ 1.36428272e-16, -7.48972195e-17,  1.00000000e+00,
        -9.11407978e-16,  1.53337709e-16],
       [-1.12028103e-15,  4.23565930e-16,  7.42638942e-18,
         1.00000000e+00,  7.45896998e-17],
       [ 5.54375616e-16, -2.55828285e-16,  7.64991346e-17,
         9.50772007e-16,  1.00000000e+00]])

In [60]:
q, r = qr(mat)
r

array([[-10.28900259,  -2.4739607 ,  -1.44789551,  -2.86436508,
          3.31108207],
       [  0.        ,  -1.12980011,  -1.80851066,   0.77224275,
          0.85635734],
       [  0.        ,   0.        ,  -1.4097521 ,   0.02061459,
          0.2685731 ],
       [  0.        ,   0.        ,   0.        ,  -0.14702742,
         -0.11311591],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.65688677]])

In [61]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.14610379, -1.14054897,  0.34224193, -0.96923649],
       [-1.32510501, -1.1095851 ,  1.80665616,  0.22564085],
       [ 0.98381684,  0.07768213,  0.45591847,  1.42252149],
       [ 0.41281574,  0.75054382, -0.25386742, -1.43947908]])

In [62]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1.14 s ± 120 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [63]:
%timeit np.random.normal(size=N)

44.9 ms ± 4.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [64]:
np.random.seed(1234)

In [65]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])